site_name: Folio CLI Documentation
site_description: Modern CLI for managing structured Markdown documentation
site_url: https://franciscoserranobaptista.github.io/folio/
repo_url: https://github.com/FranciscoSerranoBaptista/folio
repo_name: FranciscoSerranoBaptista/folio
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.tabs.link

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true
      strict: false

exclude_docs: |
  _templates/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Installation: 01-getting-started/01-installation.md
    - Quick Start: 01-getting-started/02-quick-start.md
  - Core Concepts:
    - Configuration: 02-core-concepts/01-the-folio-config.md
    - Templates: 02-core-concepts/02-templates.md
    - Indexing & Linking: 02-core-concepts/03-indexing-and-linking.md
  - Command Reference:
    - init: 03-command-reference/init.md
    - new: 03-command-reference/new.md
    - list: 03-command-reference/list.md
    - validate: 03-command-reference/validate.md
    - find: 03-command-reference/find.md
    - serve: 03-command-reference/serve.md
    - status: 03-command-reference/status.md
    - generate-nav: 03-command-reference/generate-nav.md
    - generate-prompt: 03-command-reference/generate-prompt.md
    - setup-docs: 03-command-reference/setup-docs.md
    - adr: 03-command-reference/adr.md
  - Advanced Guides:
    - ADR Workflows: 04-advanced-guides/01-adr-workflows.md
    - CI/CD Integration: 04-advanced-guides/02-ci-cd-integration.md
    - LLM Navigation: 04-advanced-guides/03-llm-navigation.md
    - Documentation Websites: 04-advanced-guides/documentation-websites.md
    - MCP Server Setup: 04-advanced-guides/04-mcp-server-setup.md
  - AI Integration:
    - Overview: ai-integration/README.md
    - Knowledge API: ai-integration/knowledge-api.md
    - AI Prompts: ai-integration/ai-prompts.md
    - Workflows: ai-integration/workflows.md
    - Troubleshooting: ai-integration/troubleshooting.md
  - Troubleshooting:
    - FAQ: 05-troubleshooting/faq.md
  - Examples:
    - Template Examples: 06-examples/template-examples.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FranciscoSerranoBaptista/folio
  generator: false

copyright: Copyright &copy; 2024 Francisco Serrano Baptista