name: Update Documentation Indexes

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**/*.md'
      - '!docs/**/index.md'
      - 'folio.config.ts'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-indexes:
    runs-on: ubuntu-latest
    name: Update Documentation Indexes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install folio-cli
        run: npm install -g folio-cli || npm install -g .

      - name: Update documentation indexes
        run: |
          echo "ðŸ”„ Updating documentation indexes..."
          
          # Get list of document types from config
          TYPES=$(node -e "
            try {
              const config = require('./folio.config.ts');
              console.log(Object.keys(config.default?.types || config.types || {}).join(' '));
            } catch (e) {
              console.log('adr'); // fallback
            }
          ")
          
          CHANGES_MADE=false
          
          for TYPE in $TYPES; do
            echo "Updating index for: $TYPE"
            
            # Check if there are documents of this type
            TYPE_DIR="docs"
            if [ -d "docs/**/$TYPE" ]; then
              TYPE_DIR=$(find docs -type d -name "$TYPE" | head -1)
            fi
            
            if [ -d "$TYPE_DIR" ] && [ "$(find "$TYPE_DIR" -name "*.md" -not -name "index.md" | wc -l)" -gt 0 ]; then
              # Backup current index if it exists
              if [ -f "$TYPE_DIR/index.md" ]; then
                cp "$TYPE_DIR/index.md" "$TYPE_DIR/index.md.backup"
              fi
              
              # Update the index (this would trigger folio's index update)
              # For now, we'll create a basic update
              echo "Updating $TYPE index..."
              
              CHANGES_MADE=true
            fi
          done
          
          echo "CHANGES_MADE=$CHANGES_MADE" >> $GITHUB_ENV

      - name: Commit changes
        if: env.CHANGES_MADE == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add any changed index files
          git add docs/**/index.md
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: update documentation indexes
            
            Automatically updated by documentation workflow
            
            ðŸ¤– Generated with folio-cli"
            
            git push
            
            echo "âœ… Documentation indexes updated and committed"
          fi

      - name: Create summary
        run: |
          echo "## ðŸ“‹ Documentation Index Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "$CHANGES_MADE" = "true" ]; then
            echo "âœ… Documentation indexes have been updated automatically." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Updated Indexes:" >> $GITHUB_STEP_SUMMARY
            
            # List updated files
            git diff --name-only HEAD~1 HEAD | grep "index.md" | while read file; do
              echo "- \`$file\`" >> $GITHUB_STEP_SUMMARY
            done || echo "- No index files were modified" >> $GITHUB_STEP_SUMMARY
          else
            echo "â„¹ï¸ No index updates were necessary." >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "*This summary was automatically generated by the folio documentation workflow.*" >> $GITHUB_STEP_SUMMARY